export const SHOW_HIDE_LOADING = 'SHOW_HIDE_LOADING';

export const SWITCH_PAGE = 'SWITCH_PAGE';

export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_BEGIN = 'REGISTER_BEGIN';

export const LOGOUT = 'LOGOUT';

export const FIRST_LOGIN_SUCCESS = 'FIRST_LOGIN_SUCCESS';
export const FIRST_LOGIN_ERROR = 'FIRST_LOGIN_ERROR';
export const FIRST_LOGIN_BEGIN = 'FIRST_LOGIN_BEGIN';

export const OPEN_SIDE_BAR = 'OPEN_SIDE_BAR';
export const CLOSE_SIDE_BAR = 'CLOSE_SIDE_BAR';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const OPEN_COUNTDONW = 'OPEN_COUNTDOWN';
export const CLOSE_COUNTDOWN = 'CLOSE_COUNTDOWN';

export const HIDE_LOADING = 'HIDE_LOADING';

export const IS_LOGIN = 'IS_LOGIN';

export const IS_ALERT = 'IS_ALERT';

export const RESET_LOGIN_FORM = 'RESET_LOGIN_FORM';
export const RESET_ALERT = 'RESET_ALERT';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const SAVE_IMAGE_FRONT = 'SAVE_IMAGE_FRONT';
export const SAVE_IMAGE_BACK = 'SAVE_IMAGE_BACK';

export const SHOW_LOADER = 'SHOW LOADER';
export const HIDE_LOADER = 'HIDE LOADER';

export const SHOW_STYLE_BODY = 'SHOW STYLE BODY';

export const HIDE_STYLE_BODY = 'HIDE STYLE BODY';

export const CONFIRM_PWD_BUY = 'CONFIRM PWD BUY CARD';

export const NUM_PAGE_BANK = 'NUMBER PAGE BANK';

export const CONFIRM_DIGITAL_CARD = 'CONFIRM DIGITAL CARD';

export const VALID_MONEY_INPUT = 'VALID MONEY INPUT';

export const NUM_PAGE_FORGOT_PASSWORD = 'NUM PAGE FORGOT PASSWORD';

export const NUM_PAGE_REGISTER = 'NUM PAGE REGISTER';
// export const NUM_PAGE_REGISTER = 'NUM PAGE REGISTER';

export const GET_ALL_USERS = 'GET ALL USERS';
export const GET_SINGLE_USER = 'GET SINGLE USER';

export const RECHARGE_BEGIN = 'RECHARGE BEGIN';
export const RECHARGE_SUCCESS = 'RECHARGE SUCCESS';
export const RECHARGE_ERROR = 'RECHARGE ERROR';

export const TRANSFER_BEGIN = 'TRANSFER BEGIN';
export const TRANSFER_SUCCESS = 'TRANSFER SUCCESS';
export const TRANSFER_ERROR = 'TRANSFER ERROR';

export const WITH_DRAW_BEGIN = 'WITH DRAW BEGIN';
export const WITH_DRAW_SUCCESS = 'WITH DRAW SUCCESS';
export const WITH_DRAW_ERROR = 'WITH DRAW ERROR';

export const BUY_CARD_BEGIN = 'BUY CARD BEGIN';
export const BUY_CARD_SUCCESS = 'BUY CARD SUCCESS';
export const BUY_CARD_ERROR = 'BUY CARD ERROR';

export const GET_HISTORY_BY_USER = 'GET HISTORY BY USER';
export const GET_HISTORY_BY_ID = 'GET HISTORY BY ID';

export const SEND_OTP_FORGOT_BEGIN = 'SEND OTP FORGOT BEGIN';
export const SEND_OTP_FORGOT_SUCCESS = 'SEND OTP FORGOT SUCCESS';
export const SEND_OTP_FORGOT_ERROR = 'SEND OTP FORGOT ERROR';

export const CONFIRM_OTP_FORGOT_BEGIN = 'CONFIRM OTP FORGOT BEGIN';
export const CONFIRM_OTP_FORGOT_SUCCESS = 'CONFIRM OTP FORGOT SUCCESS';
export const CONFIRM_OTP_FORGOT_ERROR = 'CONFIRM OTP FORGOT ERROR';

export const CONFIRM_PWD_FORGOT_BEGIN = 'CONFIRM PWD FORGOT BEGIN';
export const CONFIRM_PWD_FORGOT_SUCCESS = 'CONFIRM PWD FORGOT SUCCESS';
export const CONFIRM_PWD_FORGOT_ERROR = 'CONFIRM PWD FORGOT ERROR';

export const GET_ALL_HISTORY_USERS = 'GET ALL HISTORY USERS';

export const ALLOW_TRANSFER_MONEY_BEGIN = 'ALLOW TRANSFER MONEY BEGIN';
export const ALLOW_TRANSFER_MONEY_SUCCESS = 'ALLOW TRANSFER MONEY SUCCESS';
export const ALLOW_TRANSFER_MONEY_ERROR = 'ALLOW TRANSFER MONEY ERROR';

export const ALLOW_WITHDRAW_MONEY_BEGIN = 'ALLOW WITHDRAW MONEY BEGIN';
export const ALLOW_WITHDRAW_MONEY_SUCCESS = 'ALLOW WITHDRAW MONEY SUCCESS';
export const ALLOW_WITHDRAW_MONEY_ERROR = 'ALLOW WITHDRAW MONEY ERROR';

export const GET_ALL_USER_WITH_CONDITION_BEGIN =
  'GET ALL USER WITH CONDITION BEGIN';
export const GET_ALL_USER_WITH_CONDITION_SUCCESS =
  'GET ALL USER WITH CONDITION SUCCESS';
export const GET_ALL_USER_WITH_CONDITION_ERROR =
  'GET ALL USER WITH CONDITION ERROR';

export const UPDATE_IDENTIFY_USER_BEGIN = 'UPDATE IDENTIFY USER BEGIN';
export const UPDATE_IDENTIFY_USER_SUCCESS = 'UPDATE IDENTIFY USER SUCCESS';
export const UPDATE_IDENTIFY_USER_ERROR = 'UPDATE IDENTIFY USER ERROR';

export const GET_HISTORY_BY_USER_ID = 'GET HISTORY BY USER ID';

export const CHANGE_PASSWORD_BEGIN = 'CHANGE PASSWORD BEGIN';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE PASSWORD SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE PASSWORD ERROR';
