export const SHOW_HIDE_LOADING = 'SHOW_HIDE_LOADING';

export const SWITCH_PAGE = 'SWITCH_PAGE';

export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_BEGIN = 'REGISTER_BEGIN';

export const LOGOUT = 'LOGOUT';

export const FIRST_LOGIN_SUCCESS = 'FIRST_LOGIN_SUCCESS';
export const FIRST_LOGIN_ERROR = 'FIRST_LOGIN_ERROR';
export const FIRST_LOGIN_BEGIN = 'FIRST_LOGIN_BEGIN';

export const OPEN_SIDE_BAR = 'OPEN_SIDE_BAR';
export const CLOSE_SIDE_BAR = 'CLOSE_SIDE_BAR';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const OPEN_COUNTDONW = 'OPEN_COUNTDOWN';
export const CLOSE_COUNTDOWN = 'CLOSE_COUNTDOWN';

export const HIDE_LOADING = 'HIDE_LOADING';

export const IS_LOGIN = 'IS_LOGIN';

export const IS_ALERT = 'IS_ALERT';

export const RESET_LOGIN_FORM = 'RESET_LOGIN_FORM';
export const RESET_ALERT = 'RESET_ALERT';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const SAVE_IMAGE_FRONT = 'SAVE_IMAGE_FRONT';
export const SAVE_IMAGE_BACK = 'SAVE_IMAGE_BACK';

export const SHOW_LOADER = 'SHOW LOADER';
export const HIDE_LOADER = 'HIDE LOADER';

export const SHOW_STYLE_BODY = 'SHOW STYLE BODY';

export const HIDE_STYLE_BODY = 'HIDE STYLE BODY';

export const CONFIRM_PWD_BUY = 'CONFIRM PWD BUY CARD';

export const NUM_PAGE_BANK = 'NUMBER PAGE BANK';

export const CONFIRM_DIGITAL_CARD = 'CONFIRM DIGITAL CARD';

export const VALID_MONEY_INPUT = 'VALID MONEY INPUT';
