export const SHOW_HIDE_LOADING = 'SHOW_HIDE_LOADING';

export const SWITCH_PAGE = 'SWITCH_PAGE';

export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_BEGIN = 'REGISTER_BEGIN';
